app.s3.bucket=nbcam-spring-project
spring.config.import=aws-parameterstore:/camp-health-app/prod/

management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=never

management.info.env.enabled=true

info.team.name=${team.name}

logging.level.root=INFO
spring.jpa.hibernate.ddl-auto=validate
